Team Black and more
ITISFoundation/osparc-simcore pull request #1729
Opened 2020-08-21 10:00 UTC by odeimaiz

## What do these changes do?
- [x] Nodes tree action buttons context dependant ITISFoundation/osparc-issues#261
  - Add-new-node removed
  - Delete and Open buttons react to selection change

#### Bonus
- [x] Do not create study from template if user has no access to all services
- [x] Bugfix: Reopen study when reloading page. Also fixes some issues with "Study is already open"

## Related issue number
closes ITISFoundation/osparc-issues#261
closes ITISFoundation/osparc-issues#275

2020-08-24 13:58 UTC, ignapas reviewed
little bug: if selection hasn't change, like for example after reloading the page, the state of the buttons can be incorrect
![image](https://user-images.githubusercontent.com/4764217/91052975-771eb880-e622-11ea-916c-162ee7a86d9c.png)

2020-08-24 13:58 UTC, ignapas commented on services/web/client/source/class/osparc/store/Store.js
> +                study["state"] = state;
```suggestion
                study.state = state;
```

2020-08-24 13:58 UTC, ignapas commented on services/web/client/source/class/osparc/store/Store.js
> +                  study["state"] = state;
```suggestion
                  study.state = state;
```

2020-08-25 11:45 UTC, pcrespov approved these changes

2020-08-26 15:27 UTC, ignapas requested changes
Found a problem when opening an iteration:
![Kapture 2020-08-26 at 17 23 37](https://user-images.githubusercontent.com/4764217/91323324-0cf04a00-e7c1-11ea-9b30-196f9e53806a.gif)
And direct selection of nodes in workbench does not update tree buttons:
![Kapture 2020-08-26 at 17 26 29](https://user-images.githubusercontent.com/4764217/91323629-66f10f80-e7c1-11ea-9530-6ba913771924.gif)

2020-08-27 12:16 UTC, ignapas approved these changes
Cool! Only a minor: the sweeper window doesn't adapt to content, for example when you want to go back to the main study. It keeps the previous size from when it was holding the iteration generator.
![image](https://user-images.githubusercontent.com/4764217/91440953-b3932400-e86f-11ea-8c32-daee214b22eb.png)

2020-08-27 12:19 UTC, merged