🐛 Fix validation of DIRECTOR_V2_SERVICES_CUSTOM_CONSTRAINTS: Make it conform to docker specs
ITISFoundation/osparc-simcore pull request #3190
Opened 2022-07-14 11:41 UTC by mrnicegyu11

## What do these changes do?

Allow underscore in DIRECTOR_V2_SERVICES_CUSTOM_CONSTRAINTS in regex validation during container start

Before:
`node.labels.standard_worker==true` --> invalid
`node.labels.standardworker==true` --> valid

Now:
`node.labels.standard_worker==true` --> valid
`node.labels.standardworker==true` --> valid

2022-07-14 11:43 UTC, odeimaiz approved these changes

2022-07-14 11:43 UTC, Surfict approved these changes

2022-07-14 12:17 UTC, pcrespov approved these changes
pair reviewed. Expected test as agreed. thx

2022-07-14 13:06 UTC, GitHK requested changes

2022-07-14 13:06 UTC, GitHK commented on services/director-v2/tests/unit/test_core_settings.py
> +            # Bug from https://github.com/ITISFoundation/osparc-simcore/pull/3190
you can remove this comment, it's fine like this

2022-07-14 13:06 UTC, GitHK commented on services/director-v2/src/simcore_service_director_v2/core/settings.py
> +    strip_whitespace=True, regex=r"^[a-zA-Z0-9_. ]*(!=|==){1}[a-zA-Z0-9. ]*$"
may I suggest it like this?
```suggestion
    strip_whitespace=True, regex=r"^[a-zA-Z0-9_. ]*(!=|==){1}[a-zA-Z0-9_. ]*$"
```

2022-07-14 13:06 UTC, GitHK commented on services/director-v2/tests/unit/test_core_settings.py
> +            ["node.labels.standard_worker==true"],
Also add the following test case
```python
('["underscore_label==underscore_value"]', ["underscore_label==underscore_value"]),
```

2022-07-14 13:37 UTC, mrnicegyu11 commented
> Since you are changing these, please also add the above suggestions. Thanks!

I intentionally did not, it is unclear and untested if this is even permitted from docker.
Let's keep the changes small and atomic and not overdo it. 
This change currently prevents master from booting, so I would be happy if it gets in @GitHK

2022-07-14 13:47 UTC, GitHK commented
> > Since you are changing these, please also add the above suggestions. Thanks!
> 
> I intentionally did not, it is unclear and untested if this is even permitted from docker. Let's keep the changes small and atomic and not overdo it. This change currently prevents master from booting, so I would be happy if it gets in @GitHK

Let's have a look [at the docs](https://docs.docker.com/config/labels-custom-metadata/#label-keys-and-values). 

Apparently the key part of the label cannot contain underscores but only alphanumerical character and `.` and `-`. Please replace the `_` with `-`  in the tests and in the regex.

Regarding the value part of the label, all valid json encodable characters are ok. So `_` is ok as well.

2022-07-18 06:06 UTC, GitHK approved these changes
👍 Thanks for taking care of this

2022-07-18 06:06 UTC, GitHK commented on services/director-v2/tests/unit/test_core_settings.py
> +            # Bug from https://github.com/ITISFoundation/osparc-simcore/pull/3190
just make sure to remove this comment

2022-07-19 14:46 UTC, merged