🐛 Avoids service shutdown due to swarm networking errors
ITISFoundation/osparc-simcore pull request #3394
Opened 2022-09-27 12:40 UTC by GitHK

## What do these changes do?

## Related issue/s

## How to test

## Checklist

2022-09-27 19:33 UTC, pcrespov requested changes
The way I understand it: you have a well defined exception raised (due to network problems) and you want to ignore consecutive failures within a given time period (what you call TOLERANCE)...

Although the idea you are implementing is simple but i find *very difficult to understand* in your code mainly because:
1. the choice of variable names (very long redundant names)
2. the lack of concept encapsulation. i.e. the pieces of the logic are dispersed througout the service code!

I think the whole idea could be encapsulated in a simple error handler class that can then be used to handle this exception the way you want. An instance of this handler has be to then stored in every sidecar state object.  I wrote this and tests in  https://github.com/pcrespov/sandbox-python/blob/4db1ae54f5ef18014702407228bede431cfd16ca/py-exceptions-error-handling/test_exception_handling_with_state.py

2022-09-28 09:53 UTC, GitHK commented on services/director-v2/src/simcore_service_director_v2/modules/dynamic_sidecar/scheduler/events.py
> +                        logger.error(
I agree, in the refactor this was changed.

2022-09-28 10:29 UTC, GitHK commented on services/director-v2/tests/unit/test_modules_dynamic_sidecar_events.py
> +    assert caplog_info_level.text.count("Could not contact") > 1
I get the point and I remember seeing it somewhere but I don't remember how it works.

2022-09-28 10:53 UTC, pcrespov approved these changes

2022-09-28 16:21 UTC, elisabettai reviewed
Thank you so much for this! Really looking forward to an improved user experience.

2022-09-29 07:10 UTC, elisabettai approved these changes

2022-09-29 07:12 UTC, merged