🐛🗃️ Dask gateway: clusters cannot be deleted after usage
ITISFoundation/osparc-simcore pull request #4036
Opened 2023-03-28 10:27 UTC by sanderegg

## What do these changes do?

This fixes the issue where a cluster cannot be removed after it was used for running 1 pipeline.
The relational database was preventing it.

Since this PR changes the DB it will be blocked until after the Steering Committee demo

## Related issue/s

## How to test

2023-03-28 10:36 UTC, pcrespov requested changes
Temporarily blocked to avoid critical changes in master until Thu

2023-03-29 20:30 UTC, pcrespov approved these changes

2023-03-30 07:05 UTC, matusdrobuliak66 approved these changes

2023-03-30 09:31 UTC, GitHK approved these changes

2023-03-31 09:17 UTC, merged