✨ adding get default wallet endpoint
ITISFoundation/osparc-simcore pull request #4948
Opened 2023-10-27 20:13 UTC by matusdrobuliak66

## What do these changes do?
 - ✨ adding get default wallet endpoint (needed by Manuel to show user credits of default wallet when user logs in to the desktop application)

## Related issue/s

## How to test

## DevOps Checklist

2023-10-28 09:18 UTC, mguidon approved these changes
Thanks!

2023-10-28 09:27 UTC, pcrespov requested changes
Let me know if my arguments are convincing or not :-)

2023-10-28 09:27 UTC, pcrespov commented on api/specs/web-server/_wallets.py
> +    "/wallet",
I think this is a good approach as soon as the default wallet always exists. I interpret this as a [singleton resouce](https://cloud.google.com/apis/design/design_patterns#singleton_resources) of the user, i.e. a user always have a wallet (no need to create/delete it), and I must have update and read operations.

An alternative I have been using would be to use the existing collection's entrypoint as `GET /wallets/default`
SEE https://github.com/ITISFoundation/osparc-simcore/blob/master/services/web/server/src/simcore_service_webserver/products/_handlers.py#L59C46-L59C46

2023-10-28 09:27 UTC, pcrespov commented on services/web/server/tests/unit/with_dbs/03/wallets/test_wallets.py
> +    await assert_status(resp, web.HTTPNotFound)
IMO not found should only be used in collections, not in singletons like this. Now I would suggest the way to go as I mentioned above, i.e. `GET /wallets/default`. The client can then use exactly the same mechanisms to get and handle errors for one or multiple wallets

2023-10-28 09:27 UTC, pcrespov commented on services/web/server/tests/unit/with_dbs/03/wallets/test_wallets.py
> +@pytest.mark.parametrize("user_role,expected", [(UserRole.USER, web.HTTPOk)])
have at least one test per route that test access-right. For example see 
https://github.com/ITISFoundation/osparc-simcore/blob/master/services/web/server/tests/unit/with_dbs/03/login/test_login_unregister.py#L20-L41

2023-10-28 09:27 UTC, pcrespov commented on services/web/server/tests/unit/with_dbs/03/wallets/test_wallets.py
> +    resp = await client.get(f"{url}")
TIP you can also use `.path -> str`
```python
await client.get(url.path)

# I personally like this style for tests (at the moment)
await client.get("/v0/wallets/default")
```

2023-10-29 18:40 UTC, pcrespov approved these changes

2023-10-29 21:24 UTC, sanderegg approved these changes

2023-10-29 21:24 UTC, sanderegg commented on services/web/server/src/simcore_service_webserver/wallets/_handlers.py
> +from simcore_service_webserver.users.exceptions import UserDefaultWalletNotFoundError
relative imports

2023-10-30 06:44 UTC, matusdrobuliak66 commented on services/web/server/src/simcore_service_webserver/wallets/_handlers.py
> +from simcore_service_webserver.users.exceptions import UserDefaultWalletNotFoundError
thanks

2023-10-30 07:04 UTC, bisgaard-itis approved these changes
Looks good to me. Thanks!

2023-10-30 07:20 UTC, GitHK approved these changes

2023-10-30 07:23 UTC, merged