🐛 TIP:  Message fix (issue #1189)
ITISFoundation/osparc-simcore pull request #5062
Opened 2023-11-21 16:06 UTC by ignapas

## What do these changes do?

### Workaround [this issue](https://github.com/ITISFoundation/osparc-issues/issues/1189)

2023-11-21 16:11 UTC, pcrespov requested changes
TIP to make a good PR:
- create a readable title since it will display in the release notes
- move the issue number as an enumeration to the message. It renders and links the issues
- add the keyword "close" or "fixes" to automatically closed the resolved case

SEE https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

2023-11-21 16:11 UTC, pcrespov commented on services/static-webserver/client/source/class/osparc/desktop/StudyEditor.js
> +            // osparc.FlashMessenger.getInstance().logAs(error.message, "ERROR");
please do not leave commented code

2023-11-21 16:13 UTC, jsaq007 requested changes

2023-11-21 16:13 UTC, jsaq007 commented on services/static-webserver/client/source/class/osparc/desktop/StudyEditor.js
> +            // osparc.FlashMessenger.getInstance().logAs(error.message, "ERROR");
Haha was just writing the same

2023-11-21 16:58 UTC, pcrespov approved these changes

2023-11-21 17:03 UTC, elisabettai approved these changes
That was quick, thank you!

2023-11-21 17:09 UTC, sanderegg approved these changes
and thanks a lot!

2023-11-22 07:24 UTC, GitHK approved these changes

2023-11-22 09:54 UTC, jsaq007 approved these changes

2023-11-22 10:16 UTC, merged