🎨  App design and Web presence alignment
ITISFoundation/osparc-simcore pull request #5065
Opened 2023-11-22 08:58 UTC by jsaq007

## What do these changes do?

- Bring in colors from AppMotion
- Update login page to align with AppMotion design
- ...

![2023-11-22 09 56 25](https://github.com/ITISFoundation/osparc-simcore/assets/903587/4d35719c-4d92-4b44-ac2f-3ab3ead447de)

## Related issue/s

## How to test

## Dev Checklist

- [ ] No ENV changes or I properly updated ENV ([read the instruction](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/blob/configs/README.md?ref_type=heads#how-to-update-env-variables))

## DevOps Checklist

2023-11-22 09:26 UTC, pcrespov reviewed
:tada:

2023-11-22 10:35 UTC, sanderegg approved these changes
nice!

2023-11-22 11:27 UTC, elisabettai approved these changes

2023-11-22 11:59 UTC, matusdrobuliak66 approved these changes

2023-11-22 15:04 UTC, ignapas requested changes
Awesome! just some comments:
* Window title bar and content background should be the same
![image](https://github.com/ITISFoundation/osparc-simcore/assets/4764217/64db2778-e67c-4d7f-b337-644eafc33214)

2023-11-22 15:04 UTC, ignapas commented on services/static-webserver/client/source/class/osparc/ui/message/FlashMessage.js
> +    });
You can use `services/static-webserver/client/source/class/osparc/theme/Decoration.js` to add decorations

2023-11-22 15:05 UTC, ignapas commented
I merged latest `master` (pull before commit to avoid extra merge commits)

2023-11-27 13:35 UTC, ignapas reviewed
lgtm

2023-11-27 14:29 UTC, merged