🐛 Fix: Bring back export cMIS for osparc
ITISFoundation/osparc-simcore pull request #5499
Opened 2024-03-15 09:02 UTC by odeimaiz

## What do these changes do?

## Related issue/s

## How to test

## Dev-ops checklist

- [ ] No ENV changes or I properly updated ENV ([read the instruction](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/blob/configs/README.md?ref_type=heads#how-to-update-env-variables))

2024-03-15 09:17 UTC, elisabettai requested changes
Thanks! 
Just noticed: we should also probably remove "Billing Settings" from non-billable products. (If you click, it just goes to the Study "Overview" tab).

2024-03-15 09:22 UTC, odeimaiz commented
> Thanks! Just noticed: we should also probably remove "Billing Settings" from non-billable products. (If you click, it just goes to the Study "Overview" tab).

Good point, will do so

2024-03-15 09:29 UTC, elisabettai approved these changes

2024-03-15 09:57 UTC, pcrespov approved these changes

2024-03-15 10:35 UTC, sanderegg approved these changes

2024-03-15 11:45 UTC, matusdrobuliak66 approved these changes

2024-03-18 11:13 UTC, jsaq007 approved these changes

2024-03-18 11:33 UTC, merged