⬆️Maintenance: Upgrade of dask-based services and libs
ITISFoundation/osparc-simcore pull request #5599
Opened 2024-04-02 16:13 UTC by sanderegg

###  Highlights on updated libraries (only updated libraries are included)

- #packages before ~ 154
- #packages after ~ 148

|#|name|before|after|upgrade|count|packages|
|-|----|------|-----|-------|-----|--------|
|   1 | aio-pika                  | 9.3.0, 9.2.2, 9.1.2 | 9.4.1      | *minor*    | 4 | aws-library🧪</br>dask-sidecar⬆️</br>director-v2⬆️🧪 |
|   2 | aioboto3                  | 12.0.0          | 12.3.0     | *minor*    | 2 | aws-library🧪</br>director-v2🧪 |
|   3 | aiobotocore               | 2.7.0, 2.5.4    | 2.12.2,2.11.2 | *minor*    | 3 | aws-library🧪</br>dask-sidecar⬆️</br>director-v2🧪 |
|   4 | aiocache                  | 0.12.1          | 0.12.2     |            | 1 | director-v2⬆️ |
|   5 | aiofiles                  | 23.1.0          | 23.2.1     | *minor*    | 1 | director-v2⬆️ |
|   6 | aiohttp                   | 3.9.3, 3.8.5, 3.8.6, 3.9.1 | 3.9.3      |            | 12 | autoscaling🔧</br>aws-library🧪🔧</br>dask-sidecar⬆️🔧</br>dask-task-models-library🔧</br>director-v2⬆️🧪🔧</br>osparc-gateway-server⬆️🧪🔧 |
|   7 | aiormq                    | 6.7.6, 6.7.7    | 6.8.0      | *minor*    | 4 | aws-library🧪</br>dask-sidecar⬆️</br>director-v2⬆️🧪 |
|   8 | aiosignal                 | 1.3.1           | 🗑️ removed |  | 6 | autoscaling🔧</br>aws-library🔧</br>dask-sidecar🔧</br>dask-task-models-library🔧</br>director-v2🔧</br>osparc-gateway-server🔧 |
|   9 | alembic                   | 1.11.1          | 1.13.1     | *minor*    | 2 | director-v2⬆️🧪 |
|  10 | anyio                     | 3.7.1           | 4.3.0      | **MAJOR**  | 3 | director-v2⬆️🧪</br>osparc-gateway-server⬆️ |
|  11 | arrow                     | 1.2.3           | 1.3.0      | *minor*    | 2 | dask-sidecar⬆️</br>director-v2⬆️ |
|  12 | astroid                   | 3.0.2           | 3.1.0      | *minor*    | 6 | autoscaling🔧</br>aws-library🔧</br>dask-sidecar🔧</br>dask-task-models-library🔧</br>director-v2🔧</br>osparc-gateway-server🔧 |
|  13 | async-timeout             | 4.0.2, 4.0.3    | 4.0.3      |            | 10 | autoscaling🔧</br>aws-library🔧</br>dask-sidecar🔧</br>dask-task-models-library🔧</br>director-v2⬆️🧪🔧</br>osparc-gateway-server⬆️🧪🔧 |
|  14 | asyncpg                   | 0.28.0          | 0.29.0     | *minor*    | 1 | director-v2⬆️ |
|  15 | attrs                     | 23.1.0, 23.2.0  | 23.2.0     |            | 15 | autoscaling🔧</br>aws-library🧪🧪🔧</br>dask-sidecar⬆️🧪🔧</br>dask-task-models-library🧪🔧</br>director-v2⬆️🧪🔧</br>osparc-gateway-server⬆️🧪🔧 |
|  16 | aws-sam-translator        | 1.82.0, 1.86.0, 1.79.0 | 1.87.0     | *minor*    | 4 | autoscaling🧪</br>aws-library🧪</br>clusters-keeper🧪</br>dask-sidecar🧪 |
|  17 | aws-xray-sdk              | 2.12.1          | 2.13.0     | *minor*    | 2 | aws-library🧪</br>dask-sidecar🧪 |
|  18 | black                     | 23.12.0         | 24.3.0     | **MAJOR**  | 6 | autoscaling🔧</br>aws-library🔧</br>dask-sidecar🔧</br>dask-task-models-library🔧</br>director-v2🔧</br>osparc-gateway-server🔧 |
|  19 | boto3                     | 1.28.64, 1.28.17 | 1.34.34,1.34.51 | *minor*    | 4 | aws-library🧪🧪</br>dask-sidecar🧪</br>director-v2🧪 |
|  20 | botocore                  | 1.31.64, 1.31.17 | 1.34.34,1.34.51 | *minor*    | 5 | aws-library🧪🧪</br>dask-sidecar⬆️🧪</br>director-v2🧪 |
|  21 | botocore-stubs            | 1.31.85         | 1.34.69    | *minor*    | 1 | aws-library🧪 |
|  22 | build                     | 1.0.3, 1.1.1    | 1.2.1      | *minor*    | 7 | autoscaling🔧</br>aws-library🔧</br>clusters-keeper🔧</br>dask-sidecar🔧</br>dask-task-models-library🔧</br>director-v2🔧</br>osparc-gateway-server🔧 |
|  23 | certifi                   | 2023.7.22, 2023.11.17 | 2024.2.2   | **MAJOR**  | 7 | aws-library🧪</br>dask-sidecar⬆️🧪</br>director-v2⬆️🧪</br>osparc-gateway-server⬆️🧪 |
|  24 | cffi                      | 1.15.1          | 1.16.0     | *minor*    | 1 | osparc-gateway-server⬆️ |
|  25 | cfn-lint                  | 0.83.6, 0.86.1, 0.83.1 | 0.86.2     |            | 4 | autoscaling🧪</br>aws-library🧪</br>clusters-keeper🧪</br>dask-sidecar🧪 |
|  26 | charset-normalizer        | 3.3.2, 3.2.0    | 3.3.2      |            | 11 | aws-library🧪🔧</br>dask-sidecar⬆️🧪🔧</br>director-v2⬆️🧪🔧</br>osparc-gateway-server⬆️🧪🔧 |
|  27 | cloudpickle               | 2.2.1           | 3.0.0      | **MAJOR**  | 7 | autoscaling⬆️</br>clusters-keeper⬆️</br>dask-sidecar⬆️⬆️</br>director-v2⬆️🧪</br>osparc-gateway-server🧪 |
|  28 | colorlog                  | 6.7.0           | 6.8.2      | *minor*    | 2 | director-v2🧪</br>osparc-gateway-server⬆️ |
|  29 | coverage                  | 7.3.2, 7.3.3    | 7.4.4      | *minor*    | 5 | aws-library🧪</br>dask-sidecar🧪</br>dask-task-models-library🧪</br>director-v2🧪</br>osparc-gateway-server🧪 |
|  30 | cryptography              | 41.0.7          | 42.0.5     | **MAJOR**  | 4 | aws-library🧪</br>dask-sidecar🧪</br>director-v2🧪</br>osparc-gateway-server⬆️ |
|  31 | dask                      | 2023.12.0       | 2024.4.1   | **MAJOR**  | 1 | dask-task-models-library🧪 |
|  32 | dask-gateway              | 2023.1.1, 2023.9.0 | 2024.1.0   | **MAJOR**  | 3 | dask-sidecar⬆️</br>director-v2⬆️</br>osparc-gateway-server🧪 |
|  33 | debugpy                   | 1.8.0           | 1.8.1      |            | 1 | osparc-gateway-server🧪 |
|  34 | deepdiff                  | 6.7.1           | 7.0.0      | **MAJOR**  | 2 | autoscaling🧪</br>clusters-keeper🧪 |
|  35 | dill                      | 0.3.7           | 0.3.8      |            | 6 | autoscaling🔧</br>aws-library🔧</br>dask-sidecar🔧</br>dask-task-models-library🔧</br>director-v2🔧</br>osparc-gateway-server🔧 |
|  36 | distributed               | 2023.12.0       | 2024.4.1   | **MAJOR**  | 1 | dask-task-models-library🧪 |
|  37 | dnspython                 | 2.4.2, 2.4.0    | 2.6.1      | *minor*    | 5 | aws-library🧪</br>dask-sidecar⬆️</br>dask-task-models-library🧪</br>director-v2⬆️</br>osparc-gateway-server⬆️ |
|  38 | docker                    | 6.1.3           | 7.0.0      | **MAJOR**  | 3 | dask-sidecar🧪</br>director-v2🧪</br>osparc-gateway-server🧪 |
|  39 | ecdsa                     | 0.18.0          | 🗑️ removed |  | 2 | aws-library🧪</br>dask-sidecar🧪 |
|  40 | email-validator           | 2.1.0.post1, 2.0.0.post2 | 2.1.1      |            | 5 | aws-library🧪</br>dask-sidecar⬆️</br>dask-task-models-library🧪</br>director-v2⬆️</br>osparc-gateway-server⬆️ |
|  41 | exceptiongroup            | 1.1.2, 1.1.3    | 1.2.0      | *minor*    | 5 | dask-sidecar🧪</br>director-v2⬆️🧪</br>osparc-gateway-server⬆️🧪 |
|  42 | execnet                   | 2.0.2           | 2.1.1      | *minor*    | 1 | director-v2🧪 |
|  43 | faker                     | 24.3.0, 21.0.0, 24.7.1, 19.13.0 | 24.4.0,24.7.1 |            | 8 | autoscaling🧪</br>aws-library🧪</br>clusters-keeper🧪</br>dask-sidecar🧪</br>dask-task-models-library🧪</br>director-v2🧪</br>dynamic-sidecar🧪</br>osparc-gateway-server🧪 |
|  44 | filelock                  | 3.13.2, 3.13.1  | 3.13.3     |            | 7 | autoscaling🔧</br>aws-library🔧</br>clusters-keeper🔧</br>dask-sidecar🔧</br>dask-task-models-library🔧</br>director-v2🔧</br>osparc-gateway-server🔧 |
|  45 | flaky                     | 3.7.0           | 3.8.1      | *minor*    | 1 | director-v2🧪 |
|  46 | flask                     | 3.0.2, 3.0.0    | 3.0.3      |            | 4 | autoscaling🧪</br>aws-library🧪</br>clusters-keeper🧪</br>dask-sidecar🧪 |
|  47 | frozenlist                | 1.4.0, 1.4.1    | 1.4.1      |            | 12 | autoscaling🔧</br>aws-library🧪🔧</br>dask-sidecar⬆️🔧</br>dask-task-models-library🔧</br>director-v2⬆️🧪🔧</br>osparc-gateway-server⬆️🧪🔧 |
|  48 | fsspec                    | 2023.6.0, 2023.12.2 | 2024.3.1   | **MAJOR**  | 8 | autoscaling⬆️</br>clusters-keeper⬆️</br>dask-sidecar⬆️⬆️</br>dask-task-models-library🧪</br>director-v2⬆️🧪</br>osparc-gateway-server🧪 |
|  49 | greenlet                  | 2.0.2           | 3.0.3      | **MAJOR**  | 4 | director-v2⬆️🧪</br>osparc-gateway-server⬆️🧪 |
|  50 | h11                       | 0.14.0          | 🗑️ removed |  | 1 | osparc-gateway-server⬆️ |
|  51 | httpcore    [...]

2024-04-02 16:21 UTC, pcrespov requested changes
:-) please change the font of the PR

2024-04-02 16:28 UTC, pcrespov approved these changes

2024-04-02 16:32 UTC, bisgaard-itis approved these changes

2024-04-03 02:54 UTC, matusdrobuliak66 approved these changes

2024-04-08 15:26 UTC, merged