🎨 [Frontend] Guided Tours: add tour for TIP
ITISFoundation/osparc-simcore pull request #5933
Opened 2024-06-11 09:58 UTC by odeimaiz

## What do these changes do?

## Related issue/s

## How to test

## Dev-ops checklist

- [ ] No ENV changes or I properly updated ENV ([read the instruction](https://git.speag.com/oSparc/osparc-ops-deployment-configuration/-/blob/configs/README.md?ref_type=heads#how-to-update-env-variables))

2024-06-17 07:24 UTC, GitHK approved these changes
👍

2024-06-17 07:26 UTC, pcrespov reviewed
:+1:

2024-06-17 07:30 UTC, Konohana0608 approved these changes
Awesome thank you Odei~~

2024-06-17 08:14 UTC, elisabettai approved these changes
Super nice, wow!

Some possible improvements, but I am not sure if it's even possible:
1. Can you highlight the element in the UI that you're describing (or gray out/make darker, the ones that are out of focus)? I am thinking to something as they do in the s4l application tours
2. Do not show the filtering options in the tour. It is a very cool new feature, but I don't think it's so important to show in these "introductory" tours. I'd rather focus on the most important info and write the text it in the most concise way possible and let the users discover the rest.

For the next iteration (I assume they'll be more:
3. Text can be made more streamlined. I can help with suggestions, if needed.

2024-06-17 11:25 UTC, sanderegg approved these changes

2024-06-18 13:08 UTC, ignapas requested changes

2024-06-18 13:08 UTC, ignapas commented on services/static-webserver/client/source/class/osparc/product/tours/Tours.js
> +    },
Suggestion for a more condensed syntax: (`.then(Object.values)` is equivalent to `.then(obj => Object.values(obj))`) which is equivalent to `.then(obj => { return Object.values(obj) })`)
Also removing the catch would let you treat each error separately when you call `fetchTours` (but might not be what you want).
```suggestion
    fetchTours: function(link) {
      return osparc.utils.Utils.fetchJSON(link)
        .then(Object.values)
        .catch(console.error);
    },
```

2024-06-18 13:46 UTC, ignapas approved these changes

2024-06-18 14:21 UTC, merged